# Generated by Django 4.2 on 2024-12-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="review_text",
        ),
    ]
